import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fl_chart/fl_chart.dart';
import '../../providers/database_provider.dart';
import '../../../data/database/app_database.dart';
import '../../../../widgets/shadcn_card.dart';
import '../../widgets/scanner/premium_ocr_scanner.dart';
import '../../screens/settings/settings_screen.dart';

class SubscriptionIntelligenceDashboard extends ConsumerWidget {
  const SubscriptionIntelligenceDashboard({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Note: Use the provider name generated by @riverpod or find it in database_provider.dart
    // Based on database_provider.dart, it's appDatabaseProvider
    final db = ref.watch(appDatabaseProvider);
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      backgroundColor:
          isDark ? const Color(0xFF020817) : const Color(0xFFF8FAFC),
      appBar: AppBar(
        title: const Text(
          'Intelligence',
          style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: -1),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              // Trigger Analysis logic
            },
          ),
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (_) => const SettingsScreen()),
              );
            },
          ),
        ],
        elevation: 0,
        backgroundColor: Colors.transparent,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            PremiumOCRScanner(),
            const SizedBox(height: 24),
            _buildStatGrid(ref, db),
            const SizedBox(height: 16),
            _buildTrendChart(context),
            const SizedBox(height: 16),
            _buildSubscriptionList(db),
          ],
        ),
      ),
    );
  }

  Widget _buildStatGrid(WidgetRef ref, AppDatabase db) {
    return StreamBuilder<double>(
      stream: db.watchMonthlySubscriptionTotal(),
      builder: (context, snapshot) {
        final total = snapshot.data ?? 0.0;
        return GridView.count(
          crossAxisCount: 2,
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          mainAxisSpacing: 12,
          crossAxisSpacing: 12,
          childAspectRatio: 1.5,
          children: [
            ShadcnCard(
              title: "Monthly Burn",
              subtitle: "Total subscriptions",
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 15),
              child: Text(
                "\$${total.toStringAsFixed(2)}",
                style: const TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  letterSpacing: -1,
                ),
              ),
            ),
            ShadcnCard(
              title: "Zombie Subs",
              subtitle: "Potential savings",
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 15),
              trailing: const Icon(Icons.warning_amber_rounded,
                  color: Colors.amber, size: 20),
              child: const Text(
                "3",
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  letterSpacing: -1,
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildTrendChart(BuildContext context) {
    final theme = Theme.of(context);
    return ShadcnCard(
      title: "Cost Trend",
      subtitle: "Daily subscription expense",
      child: SizedBox(
        height: 200,
        child: LineChart(
          LineChartData(
            gridData: const FlGridData(show: false),
            titlesData: const FlTitlesData(show: false),
            borderData: FlBorderData(show: false),
            lineBarsData: [
              LineChartBarData(
                spots: [
                  const FlSpot(0, 310),
                  const FlSpot(2, 280),
                  const FlSpot(4, 350),
                  const FlSpot(6, 310),
                  const FlSpot(8, 400),
                  const FlSpot(10, 380),
                  const FlSpot(12, 420),
                ],
                isCurved: true,
                color: theme.colorScheme.primary,
                barWidth: 4,
                isStrokeCapRound: true,
                dotData: const FlDotData(show: false),
                belowBarData: BarAreaData(
                  show: true,
                  color: theme.colorScheme.primary.withValues(alpha: 0.1),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSubscriptionList(AppDatabase db) {
    return StreamBuilder<List<Subscription>>(
      stream: db.watchAllSubscriptions(),
      builder: (context, snapshot) {
        final subs = snapshot.data ?? [];
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 8),
              child: Text(
                "Active Subscriptions",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
            ),
            if (subs.isEmpty)
              const ShadcnCard(
                child: Center(
                    child: Padding(
                  padding: EdgeInsets.all(20.0),
                  child: Text("No subscriptions detected yet."),
                )),
              )
            else
              ...subs.map((sub) => Padding(
                    padding: const EdgeInsets.only(bottom: 8.0),
                    child: ShadcnCard(
                      padding: const EdgeInsets.all(12),
                      child: ListTile(
                        contentPadding: EdgeInsets.zero,
                        leading: CircleAvatar(
                          backgroundColor: Colors.grey.withValues(alpha: 0.1),
                          child: Text(sub.serviceName.isNotEmpty
                              ? sub.serviceName.substring(0, 1).toUpperCase()
                              : "?"),
                        ),
                        title: Text(
                          sub.serviceName,
                          style: const TextStyle(fontWeight: FontWeight.w600),
                        ),
                        subtitle: Text(
                            "Next: ${sub.nextRenewalDate.day}/${sub.nextRenewalDate.month}"),
                        trailing: Text(
                          "\$${sub.amount.toStringAsFixed(2)}",
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                      ),
                    ),
                  )),
          ],
        );
      },
    );
  }
}
